### ISSUE TITLE
Major upgrade to 2023

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-fhir-service#135]
We need to upgrade our server to `2023.02.02`. This involves several steps

### Upgrade server to 2023
- [x] https://github.com/kids-first/kf-api-fhir-service/issues/119
- [x] https://github.com/kids-first/kf-api-fhir-service/issues/132
- [x] https://github.com/kids-first/kf-api-fhir-service/issues/131
- [x] #134 
- [x] #142 
- [x] #136 
- [x] #145
- [ ] Enable seeding of conformance resources

### Implement OIDC with Keycloak
- [x] #138 
- [x] #139
- [x] #140  
- [x] #141 
- [x] #146 

### Data migration and testing
- [ ] https://github.com/kids-first/kf-api-fhir-service/issues/133

### Production Checklist
- [ ] Update d3b-deployment-config with prd app configuration
- [ ] Create `smilecdr` and `audit` dbs in prd rds deployment
- [ ] Update OIDC server definitions to include prd Keycloak
- [ ] Add test clients to prd Keycloak
- [ ] Protect admin console app with OIDC
- [ ] Protect admin API with OIDC
- [ ] Add callback URL to d3b Auth0 for kf-api-fhir-service-upgrade-[env].kf-strides.org
