### ISSUE TITLE
Setup auditing

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-fhir-service#161]
There was a bug that prevented us from using Smile CDR's auditing feature with OAuth2 clients. This bug has been fixed in the `2023.05.R01` docker image release.

**Tasks**

- [ ] Upload the 2023.05.R01 docker image to ECR
- [ ] Update Dockerfile to use the 2023.05.R01 image
- [ ] Configure audit features for server
